In [4]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import matplotlib.pyplot as plt
import pandas as pd
from src.model import BasicModel

plt.rcParams['figure.figsize'] = 15.7,13.27
plt.rcParams['font.family'] = 'AppleGothic'

class LEARN_INFO:
    def __init__(self, name, columns, is_contain_cluster_label=False, matching_type="general", jump=3):
        self.name = name
        self.columns = columns
        self.is_label = is_contain_cluster_label
        self.matching = matching_type
        self.jump = jump
    

# INPUT_REPORT_SIMULATION = [
#     LEARN_INFO(name="univariate", columns=['energy (kw 15min)'], is_contain_cluster_label=False),
#     LEARN_INFO(name="with cluster label", columns=['energy (kw 15min)'], is_contain_cluster_label=True),
# ]

DEFAULT_COLUMNS = [
    'energy (kw 15min)',
    ['week sin',
    'week cos'],
    ['year sin',
    'year cos'],
    'season idx',
    'weather idx',
    'avg ta',
    'avg rhm'
]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [42]:
cm = ClusterModel(name="cluster test",
                   columns=['energy (kw 15min)', 'week sin', 'week cos'],
                   is_switch=False)
cm

###### Basic Model Information ######
 - name : cluster test
 - columns : energy (kw 15min),week sin,week cos
 - datas :
                     energy (kw 15min)  week sin  week cos
Date Time
2017-01-01 00:00:00              15250  0.707107 -0.707107
2017-01-01 01:00:00              14000  0.680173 -0.733052
2017-01-01 02:00:00              14750  0.652287 -0.757972
2017-01-01 03:00:00              29500  0.623490 -0.781831
2017-01-01 04:00:00              15750  0.593820 -0.804598
 - norm_datas :
                     energy (kw 15min)  week sin  week cos  cluster energy
Date Time
2017-01-01 00:00:00          -0.719354  0.999545 -0.995537       -0.488868
2017-01-01 01:00:00          -0.811090  0.961422 -1.032194       -0.581751
2017-01-01 02:00:00          -0.756048  0.921953 -1.067402       -0.644819
2017-01-01 03:00:00           0.326432  0.881193 -1.101113       -0.162060
2017-01-01 04:00:00          -0.682660  0.839198 -1.133279       -0.420066

In [43]:
cm.norm_datas['train']

                     energy (kw 15min)  week sin  week cos  cluster energy
Date Time
2017-01-01 00:00:00          -0.719354  0.999545 -0.995537       -0.488868
2017-01-01 01:00:00          -0.811090  0.961422 -1.032194       -0.581751
2017-01-01 02:00:00          -0.756048  0.921953 -1.067402       -0.644819
2017-01-01 03:00:00           0.326432  0.881193 -1.101113       -0.162060
2017-01-01 04:00:00          -0.682660  0.839198 -1.133279       -0.420066
...                                ...       ...       ...             ...
2017-12-31 19:00:00          -1.196379  0.104470 -1.405405        0.803458
2017-12-31 20:00:00          -1.141338  0.051620 -1.408367        0.703695
2017-12-31 21:00:00          -1.214726 -0.001304 -1.409355        0.583292
2017-12-31 22:00:00          -1.196379 -0.054228 -1.408367       -0.079498
2017-12-31 23:00:00          -1.343156 -0.107078 -1.405405       -0.253796

[8760 rows x 4 columns]

In [44]:
cm.set_window()

###### [Notice] generate cluster window start ######

Total window size: 4
Input indices: [0 1 2]
Label indices: [3]
Label column name(s): ['energy (kw 15min)']

###### [Notice] generate cluster window success ######

In [45]:
for _ in cm.window.train.take(1):
    print(_)

(<tf.Tensor: shape=(32, 3, 3), dtype=float32, numpy=
array([[[-7.19353974e-01,  9.99545336e-01, -9.95537043e-01],
        [-8.11089575e-01,  9.61422503e-01, -1.03219390e+00],
        [-7.56048203e-01,  9.21953142e-01, -1.06740224e+00]],

       [[-8.11089575e-01,  9.61422503e-01, -1.03219390e+00],
        [-7.56048203e-01,  9.21953142e-01, -1.06740224e+00],
        [ 3.26432228e-01,  8.81192625e-01, -1.10111284e+00]],

       [[-7.56048203e-01,  9.21953142e-01, -1.06740224e+00],
        [ 3.26432228e-01,  8.81192625e-01, -1.10111284e+00],
        [-6.82659686e-01,  8.39197755e-01, -1.13327861e+00]],

       [[ 3.26432228e-01,  8.81192625e-01, -1.10111284e+00],
        [-6.82659686e-01,  8.39197755e-01, -1.13327861e+00],
        [-1.13898791e-01,  7.96027422e-01, -1.16385436e+00]],

       [[-6.82659686e-01,  8.39197755e-01, -1.13327861e+00],
        [-1.13898791e-01,  7.96027422e-01, -1.16385436e+00],
        [-7.72045404e-02,  7.51741946e-01, -1.19279742e+00]],

       [[-1.13898791e-01,  7.96027422e-01, -1.16385436e+00],
        [-7.72045404e-02,  7.51741946e-01, -1.19279742e+00],
        [ 1.06266722e-01,  7.06403255e-01, -1.22006750e+00]],

       [[-7.72045404e-02,  7.51741946e-01, -1.19279742e+00],
        [ 1.06266722e-01,  7.06403255e-01, -1.22006750e+00],
        [ 8.79196003e-02,  6.60074830e-01, -1.24562609e+00]],

       [[ 1.06266722e-01,  7.06403255e-01, -1.22006750e+00],
        [ 8.79196003e-02,  6.60074830e-01, -1.24562609e+00],
        [ 3.63126487e-01,  6.12821341e-01, -1.26943779e+00]],

       [[ 8.79196003e-02,  6.60074830e-01, -1.24562609e+00],
        [ 3.63126487e-01,  6.12821341e-01, -1.26943779e+00],
        [ 5.64944863e-01,  5.64708948e-01, -1.29146910e+00]],

       [[ 3.63126487e-01,  6.12821341e-01, -1.26943779e+00],
        [ 5.64944863e-01,  5.64708948e-01, -1.29146910e+00],
        [ 7.48416126e-01,  5.15804946e-01, -1.31168938e+00]],

       [[ 5.64944863e-01,  5.64708948e-01, -1.29146910e+00],
        [ 7.48416126e-01,  5.15804946e-01, -1.31168938e+00],
        [ 6.93374753e-01,  4.66177702e-01, -1.33007014e+00]],

       [[ 7.48416126e-01,  5.15804946e-01, -1.31168938e+00],
        [ 6.93374753e-01,  4.66177702e-01, -1.33007014e+00],
        [ 5.28250635e-01,  4.15896654e-01, -1.34658575e+00]],

       [[ 6.93374753e-01,  4.66177702e-01, -1.33007014e+00],
        [ 5.28250635e-01,  4.15896654e-01, -1.34658575e+00],
        [ 3.44779372e-01,  3.65032136e-01, -1.36121321e+00]],

       [[ 5.28250635e-01,  4.15896654e-01, -1.34658575e+00],
        [ 3.44779372e-01,  3.65032136e-01, -1.36121321e+00],
        [ 5.83292007e-01,  3.13655227e-01, -1.37393188e+00]],

       [[ 3.44779372e-01,  3.65032136e-01, -1.36121321e+00],
        [ 5.83292007e-01,  3.13655227e-01, -1.37393188e+00],
        [ 6.56680524e-01,  2.61837840e-01, -1.38472414e+00]],

       [[ 5.83292007e-01,  3.13655227e-01, -1.37393188e+00],
        [ 6.56680524e-01,  2.61837840e-01, -1.38472414e+00],
        [ 3.08085114e-01,  2.09652424e-01, -1.39357483e+00]],

       [[ 6.56680524e-01,  2.61837840e-01, -1.38472414e+00],
        [ 3.08085114e-01,  2.09652424e-01, -1.39357483e+00],
        [ 6.75027609e-01,  1.57171965e-01, -1.40047157e+00]],

       [[ 3.08085114e-01,  2.09652424e-01, -1.39357483e+00],
        [ 6.75027609e-01,  1.57171965e-01, -1.40047157e+00],
        [ 3.26432228e-01,  1.04469866e-01, -1.40540469e+00]],

       [[ 6.75027609e-01,  1.57171965e-01, -1.40047157e+00],
        [ 3.26432228e-01,  1.04469866e-01, -1.40540469e+00],
        [ 3.26432228e-01,  5.16198240e-02, -1.40836728e+00]],

       [[ 3.26432228e-01,  1.04469866e-01, -1.40540469e+00],
        [ 3.26432228e-01,  5.16198240e-02, -1.40836728e+00],
        [ 2.71390855e-01, -1.30423496e-03, -1.40935528e+00]],

       [[ 3.26432228e-01,  5.16198240e-02, -1.40836728e+00],
        [ 2.71390855e-01, -1.30423496e-03, -1.40935528e+00],
        [-7.72045404e-02, -5.42282946e-02, -1.40836728e+00]],

       [[ 2.71390855e-01, -1.30423496e-03, -1.40935528e+00],
        [-7.72045404e-02, -5.42282946e-02, -1.40836728e+00],
        [-4.25799936e-01, -1.07078329e-01, -1.40540469e+00]],

       [[-7.72045404e-02, -5.42282946e-02, -1.40836728e+00],
        [-4.25799936e-01, -1.07078329e-01, -1.40540469e+00],
        [-6.45965457e-01, -1.59780443e-01, -1.40047157e+00]],

       [[-4.25799936e-01, -1.07078329e-01, -1.40540469e+00],
        [-6.45965457e-01, -1.59780443e-01, -1.40047157e+00],
        [-6.45965457e-01, -2.12260902e-01, -1.39357483e+00]],

       [[-6.45965457e-01, -1.59780443e-01, -1.40047157e+00],
        [-6.45965457e-01, -2.12260902e-01, -1.39357483e+00],
        [-6.09271228e-01, -2.64446318e-01, -1.38472414e+00]],

       [[-6.45965457e-01, -2.12260902e-01, -1.39357483e+00],
        [-6.09271228e-01, -2.64446318e-01, -1.38472414e+00],
        [-3.52411449e-01, -3.16263705e-01, -1.37393188e+00]],

       [[-6.09271228e-01, -2.64446318e-01, -1.38472414e+00],
        [-3.52411449e-01, -3.16263705e-01, -1.37393188e+00],
        [ 2.71390855e-01, -3.67640615e-01, -1.36121321e+00]],

       [[-3.52411449e-01, -3.16263705e-01, -1.37393188e+00],
        [ 2.71390855e-01, -3.67640615e-01, -1.36121321e+00],
        [ 1.24613851e-01, -4.18505132e-01, -1.34658575e+00]],

       [[ 2.71390855e-01, -3.67640615e-01, -1.36121321e+00],
        [ 1.24613851e-01, -4.18505132e-01, -1.34658575e+00],
        [ 1.24613851e-01, -4.68786180e-01, -1.33007014e+00]],

       [[ 1.24613851e-01, -4.18505132e-01, -1.34658575e+00],
        [ 1.24613851e-01, -4.68786180e-01, -1.33007014e+00],
        [ 4.36515003e-01, -5.18413424e-01, -1.31168938e+00]],

       [[ 1.24613851e-01, -4.68786180e-01, -1.33007014e+00],
        [ 4.36515003e-01, -5.18413424e-01, -1.31168938e+00],
        [ 9.50234532e-01, -5.67317426e-01, -1.29146910e+00]],

       [[ 4.36515003e-01, -5.18413424e-01, -1.31168938e+00],
        [ 9.50234532e-01, -5.67317426e-01, -1.29146910e+00],
        [ 1.02362299e+00, -6.15429819e-01, -1.26943779e+00]]],
      dtype=float32)>, <tf.Tensor: shape=(32, 1, 1), dtype=float32, numpy=
array([[[-0.16206   ]],

       [[-0.42006648]],

       [[ 0.25763053]],

       [[ 0.2129094 ]],

       [[ 0.35624632]],

       [[ 0.47894272]],

       [[ 0.8057509 ]],

       [[ 0.86996585]],

       [[ 0.9789019 ]],

       [[ 0.9880755 ]],

       [[ 0.92156714]],

       [[ 0.8562055 ]],

       [[ 0.8573522 ]],

       [[ 0.8848729 ]],

       [[ 0.72204214]],

       [[ 0.9284473 ]],

       [[ 0.8034575 ]],

       [[ 0.703695  ]],

       [[ 0.583292  ]],

       [[-0.07949793]],

       [[-0.25379562]],

       [[-0.26526257]],

       [[-0.35355812]],

       [[-0.4384136 ]],

       [[-0.10357853]],

       [[-0.14141949]],

       [[ 0.39294058]],

       [[ 0.32299215]],

       [[ 0.84932536]],

       [[ 1.1245322 ]],

       [[ 2.1164238 ]],

       [[ 2.3480563 ]]], dtype=float32)>)

In [46]:
cm.norm_datas['test']

                     energy (kw 15min)  week sin  week cos  cluster energy
Date Time
2018-04-02 00:00:00          -0.774395 -0.159780 -1.400472       -0.238993
2018-04-02 01:00:00          -0.829437 -0.212261 -1.393575       -0.333230
2018-04-02 02:00:00          -0.847784 -0.264446 -1.384724       -0.359083
2018-04-02 03:00:00          -0.847784 -0.316264 -1.373932        0.096259
2018-04-02 04:00:00          -0.829437 -0.367641 -1.361213       -0.056356
...                                ...       ...       ...             ...
2018-09-19 19:00:00          -0.187287 -0.709012  1.227085       -0.442108
2018-09-19 20:00:00          -0.425800 -0.662683  1.252644       -0.837591
2018-09-19 21:00:00          -0.352411 -0.615430  1.276455       -0.995580
2018-09-19 22:00:00          -0.444147 -0.567317  1.298487       -1.057757
2018-09-19 23:00:00          -0.499188 -0.518413  1.318707       -1.142357

[4104 rows x 4 columns]

In [47]:
for _ in cm.window.test.take(1):
    print(_)

(<tf.Tensor: shape=(32, 3, 3), dtype=float32, numpy=
array([[[-0.77439535, -0.15978044, -1.4004716 ],
        [-0.8294367 , -0.2122609 , -1.3935748 ],
        [-0.84778386, -0.26444632, -1.3847241 ]],

       [[-0.8294367 , -0.2122609 , -1.3935748 ],
        [-0.84778386, -0.26444632, -1.3847241 ],
        [-0.84778386, -0.3162637 , -1.3739319 ]],

       [[-0.84778386, -0.26444632, -1.3847241 ],
        [-0.84778386, -0.3162637 , -1.3739319 ],
        [-0.8294367 , -0.3676406 , -1.3612132 ]],

       [[-0.84778386, -0.3162637 , -1.3739319 ],
        [-0.8294367 , -0.3676406 , -1.3612132 ],
        [-0.77439535, -0.41850513, -1.3465858 ]],

       [[-0.8294367 , -0.3676406 , -1.3612132 ],
        [-0.77439535, -0.41850513, -1.3465858 ],
        [-0.7010068 , -0.46878618, -1.3300701 ]],

       [[-0.77439535, -0.41850513, -1.3465858 ],
        [-0.7010068 , -0.46878618, -1.3300701 ],
        [-0.5358827 , -0.5184134 , -1.3116894 ]],

       [[-0.7010068 , -0.46878618, -1.3300701 ],
        [-0.5358827 , -0.5184134 , -1.3116894 ],
        [-0.11389879, -0.5673174 , -1.2914691 ]],

       [[-0.5358827 , -0.5184134 , -1.3116894 ],
        [-0.11389879, -0.5673174 , -1.2914691 ],
        [ 0.34477937, -0.6154298 , -1.2694378 ]],

       [[-0.11389879, -0.5673174 , -1.2914691 ],
        [ 0.34477937, -0.6154298 , -1.2694378 ],
        [ 0.60163915, -0.66268325, -1.2456261 ]],

       [[ 0.34477937, -0.6154298 , -1.2694378 ],
        [ 0.60163915, -0.66268325, -1.2456261 ],
        [ 0.60163915, -0.70901173, -1.2200675 ]],

       [[ 0.60163915, -0.66268325, -1.2456261 ],
        [ 0.60163915, -0.70901173, -1.2200675 ],
        [ 0.56494486, -0.7543504 , -1.1927974 ]],

       [[ 0.60163915, -0.70901173, -1.2200675 ],
        [ 0.56494486, -0.7543504 , -1.1927974 ],
        [ 0.60163915, -0.7986359 , -1.1638544 ]],

       [[ 0.56494486, -0.7543504 , -1.1927974 ],
        [ 0.60163915, -0.7986359 , -1.1638544 ],
        [ 0.5465978 , -0.84180623, -1.1332786 ]],

       [[ 0.60163915, -0.7986359 , -1.1638544 ],
        [ 0.5465978 , -0.84180623, -1.1332786 ],
        [ 0.21634948, -0.88380104, -1.1011128 ]],

       [[ 0.5465978 , -0.84180623, -1.1332786 ],
        [ 0.21634948, -0.88380104, -1.1011128 ],
        [ 0.12461385, -0.9245616 , -1.0674022 ]],

       [[ 0.21634948, -0.88380104, -1.1011128 ],
        [ 0.12461385, -0.9245616 , -1.0674022 ],
        [-0.1872873 , -0.9640309 , -1.0321939 ]],

       [[ 0.12461385, -0.9245616 , -1.0674022 ],
        [-0.1872873 , -0.9640309 , -1.0321939 ],
        [-0.07720454, -1.0021538 , -0.99553704]],

       [[-0.1872873 , -0.9640309 , -1.0321939 ],
        [-0.07720454, -1.0021538 , -0.99553704],
        [-0.35241145, -1.0388769 , -0.9574829 ]],

       [[-0.07720454, -1.0021538 , -0.99553704],
        [-0.35241145, -1.0388769 , -0.9574829 ],
        [-0.6276183 , -1.0741488 , -0.91808474]],

       [[-0.35241145, -1.0388769 , -0.9574829 ],
        [-0.6276183 , -1.0741488 , -0.91808474],
        [-0.77439535, -1.1079203 , -0.8773976 ]],

       [[-0.6276183 , -1.0741488 , -0.91808474],
        [-0.77439535, -1.1079203 , -0.8773976 ],
        [-0.90282524, -1.140144  , -0.8354785 ]],

       [[-0.77439535, -1.1079203 , -0.8773976 ],
        [-0.90282524, -1.140144  , -0.8354785 ],
        [-0.97621375, -1.170775  , -0.79238594]],

       [[-0.90282524, -1.140144  , -0.8354785 ],
        [-0.97621375, -1.170775  , -0.79238594],
        [-1.1046436 , -1.1997703 , -0.74818027]],

       [[-0.97621375, -1.170775  , -0.79238594],
        [-1.1046436 , -1.1997703 , -0.74818027],
        [-1.1229907 , -1.2270896 , -0.7029233 ]],

       [[-1.1046436 , -1.1997703 , -0.74818027],
        [-1.1229907 , -1.2270896 , -0.7029233 ],
        [-1.1413379 , -1.2526945 , -0.6566783 ]],

       [[-1.1229907 , -1.2270896 , -0.7029233 ],
        [-1.1413379 , -1.2526945 , -0.6566783 ],
        [-1.1229907 , -1.2765491 , -0.60951006]],

       [[-1.1413379 , -1.2526945 , -0.6566783 ],
        [-1.1229907 , -1.2765491 , -0.60951006],
        [-1.1413379 , -1.2986202 , -0.56148434]],

       [[-1.1229907 , -1.2765491 , -0.60951006],
        [-1.1413379 , -1.2986202 , -0.56148434],
        [-1.1229907 , -1.318877  , -0.5126685 ]],

       [[-1.1413379 , -1.2986202 , -0.56148434],
        [-1.1229907 , -1.318877  , -0.5126685 ],
        [-1.0496023 , -1.3372909 , -0.4631307 ]],

       [[-1.1229907 , -1.318877  , -0.5126685 ],
        [-1.0496023 , -1.3372909 , -0.4631307 ],
        [-1.0312551 , -1.3538363 , -0.4129403 ]],

       [[-1.0496023 , -1.3372909 , -0.4631307 ],
        [-1.0312551 , -1.3538363 , -0.4129403 ],
        [-0.51753557, -1.3684902 , -0.36216742]],

       [[-1.0312551 , -1.3538363 , -0.4129403 ],
        [-0.51753557, -1.3684902 , -0.36216742],
        [ 0.12461385, -1.3812319 , -0.31088313]]], dtype=float32)>, <tf.Tensor: shape=(32, 1, 1), dtype=float32, numpy=
array([[[-0.84778386]],

       [[-0.8294367 ]],

       [[-0.77439535]],

       [[-0.7010068 ]],

       [[-0.5358827 ]],

       [[-0.11389879]],

       [[ 0.34477937]],

       [[ 0.60163915]],

       [[ 0.60163915]],

       [[ 0.56494486]],

       [[ 0.60163915]],

       [[ 0.5465978 ]],

       [[ 0.21634948]],

       [[ 0.12461385]],

       [[-0.1872873 ]],

       [[-0.07720454]],

       [[-0.35241145]],

       [[-0.6276183 ]],

       [[-0.77439535]],

       [[-0.90282524]],

       [[-0.97621375]],

       [[-1.1046436 ]],

       [[-1.1229907 ]],

       [[-1.1413379 ]],

       [[-1.1229907 ]],

       [[-1.1413379 ]],

       [[-1.1229907 ]],

       [[-1.0496023 ]],

       [[-1.0312551 ]],

       [[-0.51753557]],

       [[ 0.12461385]],

       [[-0.04051029]]], dtype=float32)>)

In [51]:
_ = {
    "univariate": ['energy (kw 15min)'],
    "multivariate (week)": [
        'energy (kw 15min)',
        'week sin',
        'week cos'
    ],
    "multivariate (year)": [
        'energy (kw 15min)',
        'year sin',
        'year cos',
    ],
    "multivariate (weather)": [
        'energy (kw 15min)',
        'weather idx'
    ],
    "multivariate (avg ta)": [
        'energy (kw 15min)',
        'avg ta'
    ],
    "multivariate (avg rhm)": [
        'energy (kw 15min)',
        'avg rhm'
    ]
}

# Input Report Simulation
IRS = []
for key in _.keys():
    IRS.append(
        LEARN_INFO(name=key, 
                   columns=_[key], 
                   is_contain_cluster_label=False),
    )

# Training Model Array 
TMA = []

is_switch = False

for _ in IRS:
    cm = ClusterModel(name=_.name,
                   columns=_.columns,
                   is_switch=is_switch)
    
    cm.set_window()
    cm.set_model()
    print(cm)
    cm.training(epochs=50)
    
    cm.set_predict(is_reshape=True)
    cm.set_predict(is_reshape=True, is_val_datas=True)
    
    TMA.append(cm)
    
test_evaluate_df = pd.DataFrame();
val_evaluate_df = pd.DataFrame();

for _ in TMA:
    test_evaluate_df = test_evaluate_df.append(_.statistic(), ignore_index=True)
    val_evaluate_df = val_evaluate_df.append(_.statistic(is_val_datas=True), ignore_index=True)
    
test_evaluate_df.index = [_.name for _ in TMA]
val_evaluate_df.index = [_.name for _ in TMA]

###### [Notice] (multivariate (avg rhm)) set predict (validation) info start ######

0 / 91
50 / 91
91 / 91 complete.

###### [Notice] set predict info success ######

In [52]:
test_evaluate_df

,ecv,mae,mean dis,mean sim,mse,tss,wss
univariate,72.372349,0.268569,1.477210,0.926195,0.112089,1456.910039,402.510027
multivariate (week),66.861128,0.295644,1.609124,0.914677,0.134448,1456.910039,482.803557
multivariate (year),41.324484,0.358794,2.013889,0.838926,0.238053,1456.910039,854.849482
multivariate (weather),72.103086,0.270519,1.485291,0.926505,0.113181,1456.910039,406.432942
multivariate (avg ta),-395.526448,1.212041,6.150250,-0.371676,2.010408,1456.910039,7219.374564
multivariate (avg rhm),-269.922067,1.005096,5.091254,-0.099452,1.500816,1456.910039,5389.431727

In [53]:
val_evaluate_df

,ecv,mae,mean dis,mean sim,mse,tss,wss
univariate,63.356216,0.326233,1.761457,0.905411,0.159632,832.494756,305.057577
multivariate (week),57.374072,0.354586,1.893114,0.897221,0.185693,832.494756,354.858614
multivariate (year),-46.199919,0.724231,3.524072,0.535617,0.636895,832.494756,1217.106656
multivariate (weather),63.153058,0.328524,1.768714,0.904099,0.160517,832.494756,306.748864
multivariate (avg ta),-278.215040,1.022290,5.291247,-0.005535,1.647630,832.494756,3148.620378
multivariate (avg rhm),-181.995619,0.880277,4.525433,-0.008199,1.228466,832.494756,2347.598737

In [8]:
_ = {
    "univariate": ['energy (kw 15min)'],
    "multivariate (week)": [
        'energy (kw 15min)',
        'week sin',
        'week cos'
    ],
    "multivariate (weather)": [
        'energy (kw 15min)',
        'weather idx'
    ],
#     "multivariate (year)": [
#         'energy (kw 15min)',
#         'year sin',
#         'year cos',
#     ],

#     "multivariate (avg ta)": [
#         'energy (kw 15min)',
#         'avg ta'
#     ],
#     "multivariate (avg rhm)": [
#         'energy (kw 15min)',
#         'avg rhm'
#     ],
#     "multivariate (season)": [
#         'energy (kw 15min)',
#         'season idx'
#     ]
}

# Input Report Simulation
IRS = []

for key in _.keys():
    for jump in [3,4,6,8,12,24]:
        IRS.append(
            LEARN_INFO(name="{} / new matching {}".format(key,jump), 
                       columns=_[key], 
                       is_contain_cluster_label=True,
                       matching_type="split",
                      jump=jump),
        )

# Training Model Array 
TMA = []

is_switch = False

for _ in IRS:
    cm = ClusterModel(name=_.name,
                   columns=_.columns,
                   is_contain_cluster_label=_.is_label,
                   is_switch=is_switch,
                   matching_type=_.matching,
                   jump=_.jump)
    
    cm.set_window()
    cm.set_model()
    print(cm)
    cm.training(epochs=50)
    
    cm.set_predict(is_reshape=True)
    cm.set_predict(is_reshape=True, is_val_datas=True)
    
    TMA.append(cm)
    
test_evaluate_df = pd.DataFrame();
val_evaluate_df = pd.DataFrame();

for _ in TMA:
    test_evaluate_df = test_evaluate_df.append(_.statistic(), ignore_index=True)
    val_evaluate_df = val_evaluate_df.append(_.statistic(is_val_datas=True), ignore_index=True)
    
test_evaluate_df.index = [_.name for _ in TMA]
val_evaluate_df.index = [_.name for _ in TMA]

###### [Notice] (multivariate (weather) / new matching 24) set predict (validation) info start ######

0 / 91
50 / 91
91 / 91 complete.

###### [Notice] set predict info success ######

In [6]:
test_evaluate_df

,cos,ecv,mae,mean dis,mean sim,mse,tss,wss
univariate / new matching 3,0.941212,71.679662,0.272847,1.495252,0.931552,0.114899,1456.910039,412.601850
univariate / new matching 4,0.943768,70.812382,0.276431,1.512685,0.933367,0.118418,1456.910039,425.237335
univariate / new matching 6,0.941088,72.058786,0.265161,1.473459,0.930772,0.113361,1456.910039,407.078359
univariate / new matching 8,0.943635,71.398986,0.269621,1.489586,0.932827,0.116038,1456.910039,416.691040
univariate / new matching 12,0.942119,71.276933,0.269745,1.492652,0.931249,0.116533,1456.910039,418.469241
univariate / new matching 24,0.943051,70.662567,0.271847,1.503669,0.931989,0.119025,1456.910039,427.420005

In [7]:
val_evaluate_df

,cos,ecv,mae,mean dis,mean sim,mse,tss,wss
univariate / new matching 3,0.930975,64.203881,0.323585,1.742460,0.911777,0.155940,832.494756,298.000817
univariate / new matching 4,0.933169,63.999924,0.323424,1.745392,0.913213,0.156828,832.494756,299.698744
univariate / new matching 6,0.931975,65.514079,0.312060,1.703014,0.911682,0.150232,832.494756,287.093488
univariate / new matching 8,0.933503,65.176657,0.314214,1.711549,0.912968,0.151702,832.494756,289.902505
univariate / new matching 12,0.932474,64.997538,0.314726,1.715672,0.911702,0.152482,832.494756,291.393663
univariate / new matching 24,0.933371,64.866758,0.314488,1.716662,0.912345,0.153052,832.494756,292.482398